#!/usr/bin/env bash
#
# sync-claude-skills.sh
#
# Generate the Claude Code skill mirror at .claude/skills/ from the
# IDE-agnostic source of truth at .ai/skills/.
#
# .ai/skills/ stays authoritative. .claude/skills/ is a GENERATED artifact:
# never hand-edit it. Edit the source skill under .ai/skills/<slug>/ and
# re-run this script.
#
# Transform per skill:
#   - name:        forced to the folder slug (Claude Code requires ^[a-z0-9-]+$
#                  matching the directory name).
#   - description: passed through verbatim (truncated to 1024 chars if longer).
#   - frontmatter: only name + description are emitted; undocumented keys
#                  (metadata, tags, license, ...) are dropped from the mirror.
#   - resources:   every other top-level file/dir is copied as-is EXCEPT
#                  SKILL.md (regenerated), agents/ (other tool's config), and
#                  CLAUDE.md (claude-mem stub, not skill content).
#
# Usage:
#   sync-claude-skills.sh          Regenerate .claude/skills/ from .ai/skills/.
#   sync-claude-skills.sh --check  Exit non-zero if the mirror is out of date
#                                  (for CI / pre-commit). Writes nothing.
#
set -euo pipefail

MODE="write"
if [ "${1:-}" = "--check" ]; then
  MODE="check"
elif [ -n "${1:-}" ]; then
  echo "Unknown argument: $1 (use --check or no argument)" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SRC_DIR="$REPO_ROOT/.ai/skills"
DEST_DIR="$REPO_ROOT/.claude/skills"

[ -d "$SRC_DIR" ] || { echo "ERROR: source not found: $SRC_DIR" >&2; exit 1; }
case "$DEST_DIR" in
  */.claude/skills) : ;;
  *) echo "ERROR: refusing to operate on unexpected destination: $DEST_DIR" >&2; exit 1 ;;
esac

# Build the full mirror into $1 (which is removed and recreated).
build_into() {
  out_root="$1"
  rm -rf "$out_root"
  mkdir -p "$out_root"

  for srcdir in "$SRC_DIR"/*/; do
    [ -f "${srcdir}SKILL.md" ] || continue
    slug="$(basename "$srcdir")"
    skdest="$out_root/$slug"
    mkdir -p "$skdest"

    # description: first single-line `description:` value inside the frontmatter.
    desc="$(awk '
      BEGIN { st = 0 }
      st == 0 && /^---[[:space:]]*$/ { st = 1; next }
      st == 1 && /^---[[:space:]]*$/ { st = 2; next }
      st == 1 && /^description:[[:space:]]*/ {
        line = $0; sub(/^description:[[:space:]]*/, "", line); print line; exit
      }
    ' "${srcdir}SKILL.md")"

    if [ -z "$desc" ]; then
      echo "ERROR: $slug/SKILL.md has no single-line 'description:' in frontmatter" >&2
      exit 1
    fi
    if [ "${#desc}" -gt 1024 ]; then
      desc="$(printf '%s' "$desc" | cut -c1-1024)"
      echo "WARN: truncated description for $slug to 1024 chars" >&2
    fi

    # body: everything after the closing frontmatter delimiter.
    body_tmp="$(mktemp)"
    awk '
      BEGIN { st = 0 }
      st == 0 && /^---[[:space:]]*$/ { st = 1; next }
      st == 1 && /^---[[:space:]]*$/ { st = 2; next }
      st >= 2 { print }
    ' "${srcdir}SKILL.md" > "$body_tmp"

    {
      printf '%s\n' '---'
      printf 'name: %s\n' "$slug"
      printf 'description: %s\n' "$desc"
      printf '%s\n' '---'
      printf '%s\n' "<!-- GENERATED by sync-claude-skills from .ai/skills/$slug/SKILL.md. DO NOT EDIT; edit the source and re-run the skill. -->"
      cat "$body_tmp"
    } > "$skdest/SKILL.md"
    rm -f "$body_tmp"

    # copy bundled resources, excluding regenerated/irrelevant entries
    find "$srcdir" -mindepth 1 -maxdepth 1 \
      ! -name 'SKILL.md' ! -name 'agents' ! -name 'CLAUDE.md' \
      -exec cp -R {} "$skdest/" \;

    # claude-mem may drop empty CLAUDE.md stubs into any subdirectory;
    # never mirror them (they are not skill content).
    find "$skdest" -type f -name 'CLAUDE.md' -delete
  done
}

if [ "$MODE" = "check" ]; then
  tmp_root="$(mktemp -d)"
  trap 'rm -rf "$tmp_root"' EXIT
  build_into "$tmp_root"
  if diff -r "$tmp_root" "$DEST_DIR" >/dev/null 2>&1; then
    echo "OK: .claude/skills is in sync with .ai/skills"
    exit 0
  fi
  echo "DRIFT: .claude/skills is out of date with .ai/skills." >&2
  echo "Run: .ai/skills/sync-claude-skills/scripts/sync-claude-skills.sh" >&2
  diff -r "$tmp_root" "$DEST_DIR" >&2 || true
  exit 1
fi

# write mode: build into a staging dir, then atomically replace the mirror
staging="$(mktemp -d)"
build_into "$staging"
rm -rf "$DEST_DIR"
mkdir -p "$(dirname "$DEST_DIR")"
mv "$staging" "$DEST_DIR"

count="$(find "$DEST_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
echo "Generated $count skill(s) into .claude/skills/ from .ai/skills/"
