#!/usr/bin/env pwsh
#
# sync-claude-skills.ps1
#
# Generate the Claude Code skill mirror at .claude/skills/ from the
# IDE-agnostic source of truth at .ai/skills/. PowerShell parity for
# sync-claude-skills.sh (see that file's header for the full contract).
#
# .ai/skills/ is authoritative. .claude/skills/ is GENERATED; never hand-edit.
#
# Usage:
#   ./sync-claude-skills.ps1           Regenerate .claude/skills/.
#   ./sync-claude-skills.ps1 -Check    Exit non-zero if the mirror is stale.
#
# Note: for CI the bash script is authoritative (it runs on ubuntu-latest).
#
[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = (Resolve-Path (Join-Path $ScriptDir '../../../..')).Path
$SrcDir    = Join-Path $RepoRoot '.ai/skills'
$DestDir   = Join-Path $RepoRoot '.claude/skills'

if (-not (Test-Path -LiteralPath $SrcDir)) { throw "Source not found: $SrcDir" }
if ($DestDir -notmatch '[\\/]\.claude[\\/]skills$') { throw "Refusing to operate on unexpected destination: $DestDir" }

function Build-Into {
    param([Parameter(Mandatory)][string]$OutRoot)

    if (Test-Path -LiteralPath $OutRoot) { Remove-Item -Recurse -Force -LiteralPath $OutRoot }
    New-Item -ItemType Directory -Force -Path $OutRoot | Out-Null

    Get-ChildItem -LiteralPath $SrcDir -Directory | ForEach-Object {
        $srcdir = $_.FullName
        $slug   = $_.Name
        $skfile = Join-Path $srcdir 'SKILL.md'
        if (-not (Test-Path -LiteralPath $skfile)) { return }

        $skdest = Join-Path $OutRoot $slug
        New-Item -ItemType Directory -Force -Path $skdest | Out-Null

        $state = 0
        $desc  = $null
        $body  = New-Object System.Collections.Generic.List[string]
        foreach ($line in (Get-Content -LiteralPath $skfile)) {
            if ($state -eq 0 -and $line -match '^---\s*$') { $state = 1; continue }
            if ($state -eq 1 -and $line -match '^---\s*$') { $state = 2; continue }
            if ($state -eq 1 -and $null -eq $desc -and $line -match '^description:\s*(.*)$') { $desc = $Matches[1]; continue }
            if ($state -ge 2) { $body.Add($line) }
        }

        if ([string]::IsNullOrWhiteSpace($desc)) { throw "$slug/SKILL.md has no single-line 'description:' in frontmatter" }
        if ($desc.Length -gt 1024) { $desc = $desc.Substring(0, 1024); Write-Warning "truncated description for $slug to 1024 chars" }

        $marker = "<!-- GENERATED by sync-claude-skills from .ai/skills/$slug/SKILL.md. DO NOT EDIT; edit the source and re-run the skill. -->"
        $out = New-Object System.Collections.Generic.List[string]
        $out.Add('---'); $out.Add("name: $slug"); $out.Add("description: $desc"); $out.Add('---'); $out.Add($marker)
        $out.AddRange($body)
        # Force LF for cross-tool byte parity with the bash generator.
        [System.IO.File]::WriteAllText((Join-Path $skdest 'SKILL.md'), (($out -join "`n") + "`n"))

        Get-ChildItem -LiteralPath $srcdir -Force |
            Where-Object { $_.Name -notin @('SKILL.md', 'agents', 'CLAUDE.md') } |
            ForEach-Object { Copy-Item -LiteralPath $_.FullName -Destination $skdest -Recurse -Force }

        # claude-mem may drop empty CLAUDE.md stubs into any subdirectory;
        # never mirror them (they are not skill content).
        Get-ChildItem -LiteralPath $skdest -Recurse -File -Filter 'CLAUDE.md' -Force |
            Remove-Item -Force
    }
}

function Get-TreeMap {
    param([Parameter(Mandatory)][string]$Root)
    $map = @{}
    if (Test-Path -LiteralPath $Root) {
        Get-ChildItem -LiteralPath $Root -Recurse -File -Force | ForEach-Object {
            $rel = $_.FullName.Substring($Root.Length).TrimStart('\', '/') -replace '\\', '/'
            $map[$rel] = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash
        }
    }
    return $map
}

if ($Check) {
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("ccskills-" + [System.Guid]::NewGuid().ToString('N'))
    try {
        Build-Into -OutRoot $tmp
        $a = Get-TreeMap -Root $tmp
        $b = Get-TreeMap -Root $DestDir
        $drift = ($a.Keys + $b.Keys | Sort-Object -Unique) | Where-Object { $a[$_] -ne $b[$_] }
        if (-not $drift) { Write-Output "OK: .claude/skills is in sync with .ai/skills"; exit 0 }
        Write-Error "DRIFT: .claude/skills is out of date. Run sync-claude-skills.ps1`n  $($drift -join "`n  ")"
        exit 1
    }
    finally { if (Test-Path -LiteralPath $tmp) { Remove-Item -Recurse -Force -LiteralPath $tmp } }
}

$staging = Join-Path ([System.IO.Path]::GetTempPath()) ("ccskills-" + [System.Guid]::NewGuid().ToString('N'))
Build-Into -OutRoot $staging
if (Test-Path -LiteralPath $DestDir) { Remove-Item -Recurse -Force -LiteralPath $DestDir }
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $DestDir) | Out-Null
Move-Item -LiteralPath $staging -Destination $DestDir

$count = (Get-ChildItem -LiteralPath $DestDir -Directory).Count
Write-Output "Generated $count skill(s) into .claude/skills/ from .ai/skills/"
